---
title: "Air pollution in Ticino, Switzerland"
author: "YOUR NAME (UUN: S0000000, GitHub: USERNAME)"
date: "`r paste0('Last Compiled: ',format(Sys.time(), '%d %B, %Y'))`"
output: html_document
---

```{r load-packages, message=FALSE, warning=FALSE}
# Necessary packages that you need to add
library(tidyverse)
library(tidymodels)
```


## Exercise 1

```{r load-data, eval=FALSE}
# change eval=FALSE to eval=TRUE

# Add your code to load the data here


```


## Exercise 2 

```{r missing-variable , eval=FALSE}
# change eval=FALSE to eval=TRUE

# Add your code to identify and list the missing variables

# Store your new data below


``` 


## Exercise 3

```{r factor-variable , eval=FALSE}
# change eval=FALSE to eval=TRUE

# Add your code to create `High_PM10` and `High_PM25`

Ticino_2020_cleaned <- ___

``` 

---

## Exercise 4

```{r dataviz, eval=FALSE}
# change eval=FALSE to eval=TRUE

ggplot(____) +
  ____(____)

```

## Exercise 5

```{r boxplots, eval=FALSE}
# change eval=FALSE to eval=TRUE

ggplot(____) +
  ____(____)

```

*Add your narrative here.*

---

## Exercise 6

```{r bootstrap, eval=FALSE}
# change eval=FALSE to eval=TRUE

boot_AQ_pm10 <- Ticino_2020_cleaned %>%
  # specify the variable of interest
  ___(___) %>% 
  # generate 10000 bootstrap samples
  ___(___) %>% 
  # calculate the mean of each bootstrap sample
  calculate(stat = ___) %>%
  # calculate 90% confidence interval
    summarize(lower = ___,
            upper = ___)

boot_AQ_pm10

```

*Add your narrative here.*

---

## Exercise 7

#### Code

```{r linear-reg, eval=FALSE}
# change eval=FALSE to eval=TRUE

AQ_pm10_linear_fit <- ___

tidy(AQ_pm10_linear_fit)

```

*Add your narrative here.*


## Exercise 8

#### Code

```{r linear-reg_new, eval=FALSE}
# change eval=FALSE to eval=TRUE

# New model fit


```


```{r}
# Calculation of performance metrics

```

```{r}
# Plot the residual vs fitted values

```


*Add your narrative here.*

## Exercise 9

#### Code

```{r log-reg, eval=FALSE}
# change eval=FALSE to eval=TRUE


log_High_PM10_fit <- ___


tidy(log_High_PM10_fit)

```


*Add your narrative here.*

---

## Exercise 10

#### Code

```{r log-reg-new, eval=FALSE}
# change eval=FALSE to eval=TRUE

log_High_PM25_fit <- ___

tidy(log_High_PM25_fit)

```

*Add your narrative here.*

